spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql-db:3306/schooldb
    username: ${SCHOOLAPP_USERNAME}
    password: ${SCHOOLAPP_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

